### ISSUE TITLE
Could you please tell me the version of DGL, PyTorch, and CUDA you were using?

### ISSUE THREAD

**Issue by Ber666** [allenai/commonsense-kg-completion#10]
The code constantly yields errors about the devices. Each time I modified the code according to the information, new errors occurred. I think it might help if you can tell me the version of these packages you were using. Thanks.

**Comment by chaitanyamalaviya** [comment]
Sorry about that. Here are the package versions: 
transformers==3.0.1
torch==1.2.0 
pytorch-pretrained-bert==0.3.0 
dgl==0.3.0
I think I was using cuda 10.0.

**Comment by Simon98-AI** [comment]
> Sorry about that. Here are the package versions:
> transformers==3.0.1
> torch==1.2.0
> pytorch-pretrained-bert==0.3.0
> dgl==0.3.0
> I think I was using cuda 10.0.

Hi, can you tell me the version of python you were using
