### ISSUE TITLE
The scripts kills itself during the evaluation process.

### ISSUE THREAD

**Issue by RomanShen** [allenai/commonsense-kg-completion#17]
Hi, it's a great job. I'm trying to run the evaluation using the following command:
```bash
CUDA_VISIBLE_DEVICES={GPU_ID} python src/run_kbc_subgraph.py --dataset atomic --sim_relations --use_bias --load_model {PATH_TO_PRETRAINED_MODEL} --eval_only --write_results
```

I create a new vitural environment with conda using the requirements file in the repo. I have downloaded ATOMIC model [here](https://drive.google.com/file/d/1JXl8RFHui6y6sR33C9rMQs00awjL7tcY/view?usp=sharing) and BERT embeddings at this [link](https://drive.google.com/file/d/1R4C2s8QWwdNE9CUwtfhsYevmM7V-01YT/view?usp=sharing). However, the script kills itself when finishing the [loop](https://github.com/allenai/commonsense-kg-completion/blob/master/src/evaluation_utils.py#L155) without any error or warning. I am running the script on 128GB RAM UBUNTU 20.04 with NVIDIA TITAN RTX. So it may not be related to the resource limitation.

Could you please help me find out why it kills itself? Thank you very much!

**Comment by sincerity101** [comment]
Can you provide me with a copy of bert embedding document? The link is no longer valid. Thank you!
