### ISSUE TITLE
an Error

### ISSUE THREAD

**Issue by Diison** [allenai/commonsense-kg-completion#2]
Thank you for your great work, but when I try to train the model using the command "python -u src/run_kbc_subgraph.py --dataset conceptnet --evaluate-every 10 --n-layers 2 --graph-batch-size 60000 --sim_relations --bert_concat".

I got an error as follow:
 
Traceback (most recent call last):
  File "src/run_kbc_subgraph.py", line 532, in <module>
    main(args)
  File "src/run_kbc_subgraph.py", line 349, in main
    loss = model.get_score(e1, rel, target, graph_embeddings)
  File "/home/s2020017/work/commonsenseKBC/src/model.py", line 155, in get_score
    reg_loss = self.regularization_loss(embedding)
  File "/home/s2020017/work/commonsenseKBC/src/model.py", line 134, in regularization_loss
    dec_weight = self.decoder.module.w_relation.weight.pow(2)
  File "/home/s2020017/Anaconda_3.7/envs/commonsenseKBC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ConvTransE' object has no attribute 'module'

How can I fix it?
Thank you so much!!

**Comment by woocoder** [comment]
> 
> 
> Thank you for your great work, but when I try to train the model using the command "python -u src/run_kbc_subgraph.py --dataset conceptnet --evaluate-every 10 --n-layers 2 --graph-batch-size 60000 --sim_relations --bert_concat".
> 
> I got an error as follow:
> 
> Traceback (most recent call last):
> File "src/run_kbc_subgraph.py", line 532, in
> main(args)
> File "src/run_kbc_subgraph.py", line 349, in main
> loss = model.get_score(e1, rel, target, graph_embeddings)
> File "/home/s2020017/work/commonsenseKBC/src/model.py", line 155, in get_score
> reg_loss = self.regularization_loss(embedding)
> File "/home/s2020017/work/commonsenseKBC/src/model.py", line 134, in regularization_loss
> dec_weight = self.decoder.module.w_relation.weight.pow(2)
> File "/home/s2020017/Anaconda_3.7/envs/commonsenseKBC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in **getattr**
> type(self).**name**, name))
> AttributeError: 'ConvTransE' object has no attribute 'module'
> 
> How can I fix it?
> Thank you so much!!

You can use the ' dec_weight = self.decoder.w_relation.weight.pow(2)' instead of ' dec_weight = self.decoder.module.w_relation.weight.pow(2)'
