### ISSUE TITLE
About the pre-trained BERT ConceptNet embedding

### ISSUE THREAD

**Issue by zsun227** [allenai/commonsense-kg-completion#3]
Hello! Thanks for sharing your code and pre-trained embeddings.

I wonder how can we know the corresponding word for every bert embedding vector in the file "conceptnet_bert_embeddings.pt"? 
Looks like it's shape is  78334 x 1024. But the "cn_node_names.txt" contains 78249 entities,,,,,
So I'm not sure how to link each entity to its pre-trained BERT embedding. Could you give me some insights? thanks!

**Comment by chaitanyamalaviya** [comment]
Hi! The provide embeddings include the precomputed embeddings for the evaluation nodes as well. [Here](https://drive.google.com/file/d/1C9bdMXpcZ-9tuV2WoPrJfLewpK42ftSI/view?usp=sharing) is a list of the 78334 node names which can be linked to the provided embeddings in the same order.

**Comment by zsun227** [comment]
> Hi! The provide embeddings include the precomputed embeddings for the evaluation nodes as well. [Here](https://drive.google.com/file/d/1C9bdMXpcZ-9tuV2WoPrJfLewpK42ftSI/view?usp=sharing) is a list of the 78334 node names which can be linked to the provided embeddings in the same order.

Thank you!

**Comment by alice-cool** [comment]
Could you share the  final embedding 78334 x 1024 file?
