### ISSUE TITLE
Question about knowledge graph embedding

### ISSUE THREAD

**Issue by yichao96** [allenai/commonsense-kg-completion#9]
Hi, bro. 
I want to use the concept-knowledge graph embedding which you propose at link https://drive.google.com/file/d/1R4C2s8QWwdNE9CUwtfhsYevmM7V-01YT/view?usp=sharing

but, Only have embedding file and I can't find vocab file, 
I load the  conceptnet_bert_embeddings.pt  and it size is 78334, while the node vocab size at follow link is 78249?
https://drive.google.com/file/d/1dpSK-eV_USdQ9XvqBuj2rjvtgz_97P0E/view?usp=sharing

I  wanna know where is the node/vocab  file?

Thanks.

**Comment by JinghaoZ** [comment]
Hi, @chaitanyamalaviya 
I have the same question. Thanks!

**Comment by yichao96** [comment]
> Hi, @chaitanyamalaviya
> I have the same question. Thanks!

Hi, I have soved that question, 
When I run the src/run_kbc_subgraph.py,  during running, you will find the word_vocab variable
And the length of word_vocab is same as 78334.

Hope help you~

**Comment by JinghaoZ** [comment]
> > Hi, @chaitanyamalaviya
> > I have the same question. Thanks!
> 
> Hi, I have soved that question,
> When I run the src/run_kbc_subgraph.py, during running, you will find the word_vocab variable
> And the length of word_vocab is same as 78334.
> 
> Hope help you~

Hello~
Thanks very much. I have solved the problem following your suggestions. 
Thanks for your help!
